# docker-compose file for local development and testing with container image.
version: '3.2'

services:
  # PostgreSQL database for {{ cookiecutter.project_name }}
  {{ cookiecutter.project_slug }}-db:
    image: postgres
    env_file:
      - base.env
    volumes:
      - {{ cookiecutter.project_slug }}-postgres-data-local:/var/lib/postgresql/data
      - {{ cookiecutter.project_slug }}-postgres-backup-local:/backups

  # Debug SMTP provider
  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"

volumes:
  # Persistent volumes for postgres database data
  {{ cookiecutter.project_slug }}-postgres-data-local:
  {{ cookiecutter.project_slug }}-postgres-backup-local:
