# docker-compose file for local development and testing with container image.
version: '3.2'
services:
  devserver: &devserver
    build:
      context: .
      dockerfile: compose/Dockerfile
    expose:
      - "8000"
    ports:
      - "8000:8000"
    depends_on:
      - "{{ cookiecutter.project_slug }}-db"
      - "mailhog"
    # For devserver, mount the local directory inside the container as a volume
    # to allow local changes to be reflected without having to re-build the
    # container.
    volumes:
      - type: bind
        source: ./
        target: /usr/src/app
        read_only: true
    env_file:
      - compose/base.env
  tox:
    <<: *devserver
    entrypoint: ["tox"]
    command: []
    env_file:
      - compose/base.env
      - compose/tox.env
    volumes:
      - type: bind
        source: ./
        target: /usr/src/app
        read_only: true
      - type: volume
        source: tox-data
        target: /tmp/tox-data
  migrate:
    <<: *devserver
    command: ["migrate"]
  shell:
    <<: *devserver
    command: ["shell"]
  {{ cookiecutter.project_slug }}-db:
    image: postgres:{{ cookiecutter.postgresql_version }}
    env_file:
      - compose/base.env
    volumes:
      - postgres_data_local:/var/lib/postgresql/data
      - postgres_backup_local:/backups
  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"

volumes:
  # A persistent volume for tox to store its stuff. This allows caching of
  # virtualenvs between runs.
  tox-data:

  # Volumes for postgres to store DBs
  postgres_data_local: {}
  postgres_backup_local: {}
